---
title: Gold Trade update
author: Team Green Leaf
date: '2018-10-19'
slug: gold-trade-update
categories:
  - gld
  - metal
  - Trades
tags:
  - gld
---

On October 19, 2018 our Gold ETF options expired out of the money and as a result we lost our premium which was our maximum loss on the trade.

We entered the trade on August 6, 2018 and chose October  as our expiration month. When we entered the trade, GLD was trading around \$114 and today is it around \$116.

Even though the price of GLD is above its price on August 6th, it is not high enough to be profitable.

We learned a few things from this trade:

- We had an aggressive expectation, GLD needed to rally 5% in two months.
- The emerging currency sell-off and dollar rally caused the Gold prices to be subdued for 2 months, it seems to have bottomed now.
- In hindsight, December would have been a better expiration for our trade.

Once again this was a low risk high returns trade, and it did not work out this time. We will post new trade ideas as we see them.

